### ISSUE TITLE
DocExampleDocument not saving because no undo was registered to indicate object changed

### ISSUE THREAD

**Issue by johnholt** [acwright/DocExample#1]
I modified your ContentView.swift to register an undo using this https://developer.apple.com/forums/thread/658590 as a guide.

Would you like the change as a pull request?  

I attached my version.
[ContentView.swift.zip](https://github.com/acwright/DocExample/files/5609815/ContentView.swift.zip)

**Comment by acwright** [comment]
Sorry for the very delayed response... :) I have implemented this change. Thanks for the suggestion!
